package mods.omenamaito.registry;

import it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap;
import mods.omenamaito.OmenaMaitoTee;
import mods.omenamaito.blocks.BlockCup;
import net.fabricmc.fabric.api.block.FabricBlockSettings;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.block.Material;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;

public class OMTCups {
    public static Block EMPTY_CUP=new BlockCup(FabricBlockSettings.of(Material.GLASS).hardness(0.1f).build());
    public static Block MILK_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_CUP));
    public static Block TEA_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_CUP));
    public static Block MILK_TEA_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_CUP));
    public static Block GREEN_TEA_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_CUP));
    public static Block MILK_GREEN_TEA_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_CUP));
    public static Block BLACK_COCOA_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_CUP));
    public static Block MILK_COCOA_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_CUP));
    public static Block FRUITS_JUICE_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_CUP));
    public static Block FRUIT_SHAKES_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_CUP));
    public static Block HOT_LEMONADE_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_CUP));
    public static Block MILK_LEMONADE_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_CUP));
    public static Block COFFEE_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_CUP));
    public static Block MILK_COFFEE_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_CUP));
    public static Block EARL_GRAY_TEA_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_CUP));
    public static Block MILK_EARL_GRAY_TEA_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_CUP));
    public static Block APPLE_TEA_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_CUP));
    public static Block APPLE_MILK_TEA_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_CUP));
    public static Block LIME_JUICE_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_CUP));
    public static Block TOMATO_JUICE_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_CUP));
    public static Block BERRY_JUICE_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_CUP));
    public static Block BERRY_SHAKES_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_CUP));
    public static Block GRAPE_JUICE_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_CUP));
    public static Block MINT_TEA_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_CUP));

    public static Block EMPTY_SUMMER_CUP=new BlockCup(FabricBlockSettings.of(Material.GLASS).hardness(0.1f).build());
    public static Block MILK_SUMMER_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_SUMMER_CUP));
    public static Block TEA_SUMMER_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_SUMMER_CUP));
    public static Block MILK_TEA_SUMMER_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_SUMMER_CUP));
    public static Block GREEN_TEA_SUMMER_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_SUMMER_CUP));
    public static Block MILK_GREEN_TEA_SUMMER_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_SUMMER_CUP));
    public static Block BLACK_COCOA_SUMMER_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_SUMMER_CUP));
    public static Block MILK_COCOA_SUMMER_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_SUMMER_CUP));
    public static Block FRUITS_JUICE_SUMMER_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_SUMMER_CUP));
    public static Block FRUIT_SHAKES_SUMMER_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_SUMMER_CUP));
    public static Block HOT_LEMONADE_SUMMER_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_SUMMER_CUP));
    public static Block MILK_LEMONADE_SUMMER_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_SUMMER_CUP));
    public static Block COFFEE_SUMMER_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_SUMMER_CUP));
    public static Block MILK_COFFEE_SUMMER_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_SUMMER_CUP));
    public static Block EARL_GRAY_TEA_SUMMER_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_SUMMER_CUP));
    public static Block MILK_EARL_GRAY_TEA_SUMMER_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_SUMMER_CUP));
    public static Block APPLE_TEA_SUMMER_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_SUMMER_CUP));
    public static Block APPLE_MILK_TEA_SUMMER_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_SUMMER_CUP));
    public static Block LIME_JUICE_SUMMER_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_SUMMER_CUP));
    public static Block TOMATO_JUICE_SUMMER_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_SUMMER_CUP));
    public static Block BERRY_JUICE_SUMMER_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_SUMMER_CUP));
    public static Block BERRY_SHAKES_SUMMER_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_SUMMER_CUP));
    public static Block GRAPE_JUICE_SUMMER_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_SUMMER_CUP));
    public static Block MINT_TEA_SUMMER_CUP=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_SUMMER_CUP));

    public static Block EMPTY_YUNOMI=new BlockCup(FabricBlockSettings.of(Material.GLASS).hardness(0.1f).build());
    public static Block MILK_YUNOMI=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_YUNOMI));
    public static Block TEA_YUNOMI=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_YUNOMI));
    public static Block MILK_TEA_YUNOMI=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_YUNOMI));
    public static Block GREEN_TEA_YUNOMI=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_YUNOMI));
    public static Block MILK_GREEN_TEA_YUNOMI=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_YUNOMI));
    public static Block BLACK_COCOA_YUNOMI=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_YUNOMI));
    public static Block MILK_COCOA_YUNOMI=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_YUNOMI));
    public static Block FRUITS_JUICE_YUNOMI=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_YUNOMI));
    public static Block FRUIT_SHAKES_YUNOMI=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_YUNOMI));
    public static Block HOT_LEMONADE_YUNOMI=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_YUNOMI));
    public static Block MILK_LEMONADE_YUNOMI=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_YUNOMI));
    public static Block COFFEE_YUNOMI=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_YUNOMI));
    public static Block MILK_COFFEE_YUNOMI=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_YUNOMI));
    public static Block EARL_GRAY_TEA_YUNOMI=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_YUNOMI));
    public static Block MILK_EARL_GRAY_TEA_YUNOMI=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_YUNOMI));
    public static Block APPLE_TEA_YUNOMI=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_YUNOMI));
    public static Block APPLE_MILK_TEA_YUNOMI=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_YUNOMI));
    public static Block LIME_JUICE_YUNOMI=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_YUNOMI));
    public static Block TOMATO_JUICE_YUNOMI=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_YUNOMI));
    public static Block BERRY_JUICE_YUNOMI=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_YUNOMI));
    public static Block BERRY_SHAKES_YUNOMI=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_YUNOMI));
    public static Block GRAPE_JUICE_YUNOMI=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_YUNOMI));
    public static Block MINT_TEA_YUNOMI=new BlockCup(Block.Settings.copy(OMTCups.EMPTY_YUNOMI));

    public static void init() {
        register("empty_cup",EMPTY_CUP);
        register("hot_milk_cup",MILK_CUP);
        register("tea_cup",TEA_CUP);
        register("milk_tea_cup",MILK_TEA_CUP);
        register("green_tea_cup",GREEN_TEA_CUP);
        register("milk_green_tea_cup",MILK_GREEN_TEA_CUP);
        register("black_cocoa_cup",BLACK_COCOA_CUP);
        register("milk_cocoa_cup",MILK_COCOA_CUP);
        register("fruits_juice_cup",FRUITS_JUICE_CUP);
        register("fruit_shakes_cup",FRUIT_SHAKES_CUP);
        register("hot_lemonade_cup",HOT_LEMONADE_CUP);
        register("milk_lemonade_cup",MILK_LEMONADE_CUP);
        register("coffee_cup",COFFEE_CUP);
        register("milk_coffee_cup",MILK_COFFEE_CUP);
        register("earl_gray_tea_cup",EARL_GRAY_TEA_CUP);
        register("milk_earl_gray_tea_cup",MILK_EARL_GRAY_TEA_CUP);
        register("apple_tea_cup",APPLE_TEA_CUP);
        register("apple_milk_tea_cup",APPLE_MILK_TEA_CUP);
        register("lime_juice_cup",LIME_JUICE_CUP);
        register("tomato_juice_cup",TOMATO_JUICE_CUP);
        register("berry_juice_cup",BERRY_JUICE_CUP);
        register("berry_shakes_cup",BERRY_SHAKES_CUP);
        register("grape_juice_cup",GRAPE_JUICE_CUP);
        register("mint_tea_cup",MINT_TEA_CUP);

        register("empty_summer_cup",EMPTY_SUMMER_CUP);
        register("hot_milk_summer_cup",MILK_SUMMER_CUP);
        register("tea_summer_cup",TEA_SUMMER_CUP);
        register("milk_tea_summer_cup",MILK_TEA_SUMMER_CUP);
        register("green_tea_summer_cup",GREEN_TEA_SUMMER_CUP);
        register("milk_green_tea_summer_cup",MILK_GREEN_TEA_SUMMER_CUP);
        register("black_cocoa_summer_cup",BLACK_COCOA_SUMMER_CUP);
        register("milk_cocoa_summer_cup",MILK_COCOA_SUMMER_CUP);
        register("fruits_juice_summer_cup",FRUITS_JUICE_SUMMER_CUP);
        register("fruit_shakes_summer_cup",FRUIT_SHAKES_SUMMER_CUP);
        register("hot_lemonade_summer_cup",HOT_LEMONADE_SUMMER_CUP);
        register("milk_lemonade_summer_cup",MILK_LEMONADE_SUMMER_CUP);
        register("coffee_summer_cup",COFFEE_SUMMER_CUP);
        register("milk_coffee_summer_cup",MILK_COFFEE_SUMMER_CUP);
        register("earl_gray_tea_summer_cup",EARL_GRAY_TEA_SUMMER_CUP);
        register("milk_earl_gray_tea_summer_cup",MILK_EARL_GRAY_TEA_SUMMER_CUP);
        register("apple_tea_summer_cup",APPLE_TEA_SUMMER_CUP);
        register("apple_milk_tea_summer_cup",APPLE_MILK_TEA_SUMMER_CUP);
        register("lime_juice_summer_cup",LIME_JUICE_SUMMER_CUP);
        register("tomato_juice_summer_cup",TOMATO_JUICE_SUMMER_CUP);
        register("berry_juice_summer_cup",BERRY_JUICE_SUMMER_CUP);
        register("berry_shakes_summer_cup",BERRY_SHAKES_SUMMER_CUP);
        register("grape_juice_summer_cup",GRAPE_JUICE_SUMMER_CUP);
        register("mint_tea_summer_cup",MINT_TEA_SUMMER_CUP);

        register("empty_yunomi",EMPTY_YUNOMI);
        register("hot_milk_yunomi",MILK_YUNOMI);
        register("tea_yunomi",TEA_YUNOMI);
        register("milk_tea_yunomi",MILK_TEA_YUNOMI);
        register("green_tea_yunomi",GREEN_TEA_YUNOMI);
        register("milk_green_tea_yunomi",MILK_GREEN_TEA_YUNOMI);
        register("black_cocoa_yunomi",BLACK_COCOA_YUNOMI);
        register("milk_cocoa_yunomi",MILK_COCOA_YUNOMI);
        register("fruits_juice_yunomi",FRUITS_JUICE_YUNOMI);
        register("fruit_shakes_yunomi",FRUIT_SHAKES_YUNOMI);
        register("hot_lemonade_yunomi",HOT_LEMONADE_YUNOMI);
        register("milk_lemonade_yunomi",MILK_LEMONADE_YUNOMI);
        register("coffee_yunomi",COFFEE_YUNOMI);
        register("milk_coffee_yunomi",MILK_COFFEE_YUNOMI);
        register("earl_gray_tea_yunomi",EARL_GRAY_TEA_YUNOMI);
        register("milk_earl_gray_tea_yunomi",MILK_EARL_GRAY_TEA_YUNOMI);
        register("apple_tea_yunomi",APPLE_TEA_YUNOMI);
        register("apple_milk_tea_yunomi",APPLE_MILK_TEA_YUNOMI);
        register("lime_juice_yunomi",LIME_JUICE_YUNOMI);
        register("tomato_juice_yunomi",TOMATO_JUICE_YUNOMI);
        register("berry_juice_yunomi",BERRY_JUICE_YUNOMI);
        register("berry_shakes_yunomi",BERRY_SHAKES_YUNOMI);
        register("grape_juice_yunomi",GRAPE_JUICE_YUNOMI);
        register("mint_tea_yunomi",MINT_TEA_YUNOMI);
    }
    public static void register(String name, Block block){
        Identifier id = OmenaMaitoTee.getId(name);
        Registry.register(Registry.BLOCK, id, block);
    }
}
